workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
      java: 11
    
    scripts:
      - name: Clean workspace
        script: |
          # Clean Gradle caches and workspace
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/
          rm -rf ~/.android/build-cache/
          rm -rf .gradle
          rm -rf build
          rm -rf app/build

      - name: Fix line endings
        script: |
          # Install dos2unix
          apt-get update
          apt-get install -y dos2unix
          
          # Fix line endings for all script files
          find . -type f -name "*.sh" -exec dos2unix {} \;
          find . -type f -name "gradlew" -exec dos2unix {} \;
          dos2unix gradlew

      - name: Create project structure
        script: |
          # Create necessary directories
          mkdir -p src/main/java/com/example/scamcalldetector
          mkdir -p src/main/res/values
          mkdir -p src/main/res/layout
          mkdir -p gradle/wrapper
          
          # Create local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
          # Set up Gradle wrapper
          cd gradle/wrapper
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          wget https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradle/wrapper/gradle-wrapper.jar
          cd ../..
          
          # Create gradle-wrapper.properties
          echo "distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists" > gradle/wrapper/gradle-wrapper.properties
          
          # Fix permissions
          chmod +x gradlew
          
      - name: Build Android app
        script: |
          # Set Gradle properties
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" > ~/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=2048m" >> ~/.gradle/gradle.properties
          echo "org.gradle.workers.max=2" >> ~/.gradle/gradle.properties
          
          # Build with clean workspace
          ./gradlew clean --no-daemon
          ./gradlew assembleDebug --no-daemon --info --stacktrace --warning-mode=all
    artifacts:
      - build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true 
