workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
      java: 11
      android_sdk: latest
    scripts:
      - name: Set up build environment
        script: |
          # Create fresh working directory
          WORK_DIR="/tmp/android-build"
          rm -rf "$WORK_DIR"
          mkdir -p "$WORK_DIR"
          cp -r . "$WORK_DIR/"
          cd "$WORK_DIR"
          
          # Clean any existing Gradle state
          rm -rf ~/.gradle
          mkdir -p ~/.gradle
          
          # Set up Gradle properties
          echo "org.gradle.daemon=false" > ~/.gradle/gradle.properties
          echo "org.gradle.parallel=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m" >> ~/.gradle/gradle.properties
          echo "android.useAndroidX=true" >> ~/.gradle/gradle.properties
          
          # Create local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
          # Set up Gradle wrapper
          mkdir -p gradle/wrapper
          cd gradle/wrapper
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          wget https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradle/wrapper/gradle-wrapper.jar
          cd ../..
          
          # Create gradle-wrapper.properties
          echo "distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists" > gradle/wrapper/gradle-wrapper.properties
          
          # Fix permissions
          chmod +x gradlew
          
          # Debug info
          pwd
          ls -la
          echo "Content of build.gradle:"
          cat build.gradle
          echo "Content of settings.gradle:"
          cat settings.gradle

      - name: Build Android app
        script: |
          cd /tmp/android-build
          # Build with explicit tasks
          ./gradlew tasks --all
          ./gradlew clean
          ./gradlew compileDebugSources --stacktrace
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - /tmp/android-build/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - paulf.hague@gmail.com
        notify:
          success: true
          failure: true 
